name: PR Validate (Factory)

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Init (again for safety with Cloud)
        run: terraform init -input=false -reconfigure

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan -refresh=false
