name: PR Validate (Factory)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5   # adjust to match your repo version

      # Terraform Init
      - name: Terraform Init
        working-directory: environments/dev/storage_test   # 👈 update if different
        run: terraform init -input=false

      # Terraform Plan
      - name: Terraform Plan (save plan)
        working-directory: environments/dev/storage_test
        run: terraform plan -input=false -out=tfplan

      # Terraform Show → JSON
      - name: Terraform Show (to JSON)
        working-directory: environments/dev/storage_test
        run: terraform show -json tfplan > plan.json

      # Install Wiz CLI
      - name: Install Wiz CLI
        run: |
          curl -sL https://get.wiz.io/wiz-cli.sh | bash
          mv wiz /usr/local/bi
